import './common/modal/trailer-mod/trailer.js';
import './common/modal/trailer-error-mod/trailer-error.js';
import './common/modal/footer-mod/footer-mod.js';
import './main-blocks/hero/hero.js';
import './common/theme-switching.js';
import './main-blocks/header/header.js';
import './main-blocks/hero/API';
import './main-blocks/hero/hero';
import './common/stickyButton/sticky.js';
import './common/modal/trailer-error-mod/trailer-error.js'
